/**
 * fetch-gita.mjs
 * Run: node scripts/fetch-gita.mjs
 * Source: https://vedicscriptures.github.io (public domain, no auth)
 * Fetches all 18 chapters + all ~700 verses and writes src/data/gita.ts
 */

import { writeFileSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const BASE = 'https://vedicscriptures.github.io';

// Known verse counts per chapter (authoritative)
const VERSE_COUNTS = [47,72,43,42,29,47,30,28,34,42,55,20,35,27,20,24,28,78];

async function fetchJSON(url, retries = 3) {
  for (let i = 0; i < retries; i++) {
    try {
      const res = await fetch(url, { signal: AbortSignal.timeout(15000) });
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      return await res.json();
    } catch (e) {
      if (i === retries - 1) throw e;
      await new Promise(r => setTimeout(r, 1000 * (i + 1)));
    }
  }
}

async function sleep(ms) { return new Promise(r => setTimeout(r, ms)); }

async function main() {
  console.log('📖 Fetching Bhagavad Gita synonyms from praneshp1org …');
  let synonymsMap = new Map();
  try {
    const synonymsRaw = await fetchJSON('https://raw.githubusercontent.com/praneshp1org/Bhagavad-Gita-JSON-data/master/verse.json');
    for (const item of synonymsRaw) {
      const key = `${item.chapter_number}_${item.verse_number}`;
      synonymsMap.set(key, (item.word_meanings ?? '').trim());
    }
    console.log(`✅ Loaded ${synonymsMap.size} word meanings.\n`);
  } catch (err) {
    console.error('⚠️ Could not load synonyms, proceeding with empty strings', err);
  }

  console.log('📖 Fetching Bhagavad Gita from vedicscriptures.github.io …\n');

  const fullData = [];

  for (let chNum = 1; chNum <= 18; chNum++) {
    // Fetch chapter metadata
    const ch = await fetchJSON(`${BASE}/chapter/${chNum}/`);
    const verseCount = VERSE_COUNTS[chNum - 1];
    console.log(`Chapter ${chNum}: ${ch.translation} (${verseCount} verses)`);

    const verses = [];

    // Fetch all verses for this chapter (with concurrency of 5)
    const BATCH = 5;
    for (let v = 1; v <= verseCount; v += BATCH) {
      const batch = [];
      for (let b = v; b < v + BATCH && b <= verseCount; b++) {
        batch.push(
          fetchJSON(`${BASE}/slok/${chNum}/${b}/`).then(d => {
            const key = `${chNum}_${b}`;
            return {
              verse: b,
              sanskrit: (d.slok ?? '').trim(),
              transliteration: (d.transliteration ?? '').trim(),
              // prefer Swami Sivananda English translation, fall back to Prabhupada/others
              meaning: (d.siva?.et ?? d.prabhu?.et ?? d.tej?.et ?? d.purohit?.et ?? d.adi?.et ?? d.abhinav?.et ?? d.ms?.et ?? '').trim(),
              // Hindi meaning
              meaningHindi: (d.tej?.ht ?? d.siva?.ht ?? '').trim(),
              wordMeanings: synonymsMap.get(key) || '',
              purport: (d.prabhu?.ec ?? d.siva?.ec ?? '').trim(),
            };
          })
        );
      }
      const results = await Promise.all(batch);
      verses.push(...results);
      process.stdout.write(`  ${verses.length}/${verseCount}\r`);
      await sleep(150);
    }
    console.log(`  ✅ ${verses.length} verses fetched`);

    fullData.push({
      chapter: chNum,
      name: ch.name ?? '',               // Sanskrit Devanagari
      nameTransliterated: ch.transliteration ?? '',
      nameTranslated: ch.translation ?? '',
      nameEnglish: ch.meaning?.en ?? '',
      versesCount: verseCount,
      summary: ch.summary?.en ?? '',
      verses,
    });

    await sleep(300);
  }

  // Build TypeScript file
  const ts = `// AUTO-GENERATED by scripts/fetch-gita.mjs — DO NOT EDIT MANUALLY
// Source: vedicscriptures.github.io (public domain, no auth required)
// Translations: Swami Sivananda / Swami Tejomayananda / multiple commentators

export interface GitaVerse {
  verse: number;
  sanskrit: string;
  transliteration: string;
  meaning: string;
  meaningHindi: string;
  wordMeanings: string;
  purport: string;
}

export interface GitaChapter {
  chapter: number;
  /** Devanagari Sanskrit name */
  name: string;
  /** IAST transliteration */
  nameTransliterated: string;
  /** Common English name */
  nameTranslated: string;
  /** Short English subtitle */
  nameEnglish: string;
  versesCount: number;
  summary: string;
  verses: GitaVerse[];
}

export const GITA_CHAPTERS: GitaChapter[] = ${JSON.stringify(fullData, null, 2)};

export function getChapter(n: number): GitaChapter | undefined {
  return GITA_CHAPTERS.find(c => c.chapter === n);
}

export function getVerse(chapter: number, verse: number): GitaVerse | undefined {
  return getChapter(chapter)?.verses.find(v => v.verse === verse);
}

export const TOTAL_VERSES = ${fullData.reduce((s,c)=>s+c.verses.length,0)};

export const CHAPTER_VERSE_COUNTS = [${VERSE_COUNTS.join(',')}] as const;
`;

  const outDir = join(__dirname, '..', 'src', 'data');
  mkdirSync(outDir, { recursive: true });
  writeFileSync(join(outDir, 'gita.ts'), ts, 'utf-8');

  const total = fullData.reduce((s, c) => s + c.verses.length, 0);
  console.log(`\n✨ Done! src/data/gita.ts written`);
  console.log(`   Chapters: ${fullData.length} | Total verses: ${total}`);
}

main().catch(e => { console.error('❌', e); process.exit(1); });
